const CHARACTERS = [
  {
    id:    'kaido',
    name:  'Kaido',
    title: 'King of Beasts',
    color: { main: '#60a5fa', dark: '#1e3a8a', mid: '#2563eb', glow: 'rgba(96,165,250,' },
    stats: {
      hp:      200,
      damage:  25,
      speed:   2.5,
      hpBar:   1.0,
      dmgBar:  0.6,
      spdBar:  0.3,
    },
    attack: {
      name: 'Fire Breath',
      desc: 'Medium-range fire breath beam',
    },
    images: {
      idle_down: 'assets/kaido_idle_down.jpg',
      idle_up:   'assets/kaido_idle_up.jpg',
      idle_side: 'assets/kaido_idle_side.jpg',
      charge:    'assets/kaido_charge.jpg',
      attack:    'assets/kaido_attack.jpg',
    },
    flavor: 'An unstoppable force.\nHigh HP. Measured destruction.',
  },
  {
    id:    'dio',
    name:  'Dio',
    title: 'The Vampire Lord',
    color: { main: '#eab308', dark: '#713f12', mid: '#ca8a04', glow: 'rgba(234,179,8,' },
    stats: {
      hp:      80,
      damage:  45,
      speed:   3.5,
      hpBar:   0.35,
      dmgBar:  1.0,
      spdBar:  0.6,
    },
    attack: {
      name: 'Knife Barrage',
      desc: 'Throws arcing knives with gravity',
    },
    images: {
      idle_down: 'assets/dio_idle_down.jpg',
      idle_up:   'assets/dio_idle_up.jpg',
      idle_side: 'assets/dio_idle_side.jpg',
      attack:    'assets/dio_attack.jpg',
    },
    flavor: 'It was me, Dio!\nGlass cannon. Devastating output.',
  },
  {
    id:    'levi',
    name:  'Levi',
    title: "Humanity's Strongest Soldier",
    color: { main: '#4ade80', dark: '#14532d', mid: '#16a34a', glow: 'rgba(74,222,128,' },
    stats: {
      hp:      120,
      damage:  15,
      speed:   5.5,
      hpBar:   0.55,
      dmgBar:  0.38,
      spdBar:  1.0,
    },
    attack: {
      name: 'Blade Sweep',
      desc: 'Semi-circle sword slash',
    },
    images: {
      idle_down: 'assets/levi_idle_down.jpg',
      idle_up:   'assets/levi_idle_up.jpg',
      idle_side: 'assets/levi_idle_side.jpg',
      attack:    'assets/levi_attack.jpg',
    },
    flavor: 'No time to hesitate.\nLightning speed. Precision strikes.',
  },
];
